openedx/openedx-wordpress-ecommerce

.gitignore
includes/class-openedx-woocommerce-plugin.php
test/HelloTest.php

- Created a test case in HelloTest file that will always give an OK result to check the workflow is working correctly.
- Added gitignore to avoid composer files

fix: added dummy-test to test git workflow & gitignore file

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

This PR adds issue and PR templates.
These changes were inspired by [the eox-core templates](https://github.com/eduNEXT/eox-core/tree/master/.github). To test it, you can create a PR or issue in eox-core to see the template.
Another reference:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

feat: add issue and pr templates

---

admin/Openedx_Woocommerce_Plugin_Admin.php
admin/views/Openedx_Woocommerce_Plugin_Enrollment_Info_Form.php
composer.json
includes/Openedx_Woocommerce_Plugin.php
includes/Openedx_Woocommerce_Plugin_Activator.php
includes/Openedx_Woocommerce_Plugin_Deactivator.php
includes/Openedx_Woocommerce_Plugin_Loader.php
includes/Openedx_Woocommerce_Plugin_i18n.php
includes/model/Openedx_Woocommerce_Plugin_Enrollment.php
includes/model/Openedx_Woocommerce_Plugin_Post_Type.php
openedx-woocommerce-plugin.php
public/Openedx_Woocommerce_Plugin_Public.php

A refactoring of the code was done in order to decouple the code from the Openedx_Woocommerce_Plugin_Admin file for:
- Facilitate future implementations
- Facilitate the testing process of the class.
In addition, namespace and their respective "use" were declared if necessary in each class in order to make easier and cleaner the invocation of the classes between the plugin files. It will benefit us as developers for a better understanding and improve the scalability of the code.
To test, perform the normal flow of activation and deactivation of the plugin and make the flow of an "Enrollment Request" in the dashboard (with the functionalities that we have so far) to check that there is no invocation to an existing class that cannot be found because of the namespace statements.

fix: code refactoring and namespace/use statements.

---

admin/views/Openedx_Woocommerce_Plugin_Enrollment_Info_Form.php
includes/Openedx_Woocommerce_Plugin.php
includes/model/Openedx_Woocommerce_Plugin_Enrollment.php

The form's ergonomics were enhanced to make it more user-friendly. The action selection area and the button to execute the actions were integrated into the same form to avoid disconnection. Additionally, a box was added to hold logs in the future (there is a temporary function that generates logs). Furthermore, the message that previously said "Post updated" was modified to "Enrollment action executed."
To test, simply access the form, fill in or modify the information, and create/update the enrollment.
The get_logs function will be temporarily present only as an example to showcase the visualization. Once the logging functionality is developed, these placeholder logs will be replaced with the real ones.

style: ergonomic design form

---

admin/css/openedx-woocommerce-plugin-admin.css
admin/views/Openedx_Woocommerce_Plugin_Settings.php
includes/Openedx_Woocommerce_Plugin.php

An element is created in the Settings submenu on the Dashboard called 'Open edX Sync,' which, upon entering, displays a form where the user will input their domain, ID, and other details to be synchronized with the plugin.
Simply access the option and fill out the form.
For the text fields, a function named custom_sanitize_alphanumeric was created, which currently defaults to accepting only alphanumeric values, so that if special characters are entered, they will be removed.
The plugin's settings information is stored in the WordPress database because there is a hook available to query it easily in the case of configurations.
The frontend looks like this:

feat: settings section for openedx plugin configuration

---

.github/workflows/continuous-integration.yml
.github/workflows/wordpress-cs-check.yml

A parameter is corrected in the CI workflow that was incorrect due to the filename. Previously, it was named 'class-openedx-woocommerce-plugin', and now it is named 'openedx-woocommerce-plugin'. Additionally, the '--no-dev' property is added to the composer install in the WPCS workflow to install only the dependencies required for production, rather than all of them.
To test, please download the file and try it either locally or on the staging environment.

fix: ci and wpcs workflow fixes

---

admin/views/class-openedx-woocommerce-plugin-settings.php

Fixed an issue where a WordPress fatal error occurred when there was an error in the form information on the plugin's settings page, causing a severe disruption in the workflow. Now, the error is displayed as a card above the form. to the description of corresponding configuration changes. Remember to correctly annotate these
changes.
Go to the staging and trigger an error by entering incorrect information in the form and attempting to generate a new token.

fix: handler of fatal error in settings page corrected

---

admin/class-openedx-woocommerce-plugin-admin.php
includes/class-openedx-woocommerce-plugin.php
includes/model/class-openedx-woocommerce-plugin-enrollment.php

A functionality has been created that allows a WooCommerce order, which has already been paid and is in the 'processing' state, to automatically create an Enrollment Request with the order information. In this case, the email used for processing will be the one associated with the billing information of the order.
This pull request includes only the 'happy path,' which means it works when all the information is correct and handles very basic errors. In other words, if there is a failure in the API request, it will be displayed in the notes, but if there are other types of errors, there is a possibility that the process may be interrupted.
To test it:
1. Go to the test product: https://stagingwoocommerceplugin.kinsta.cloud/?product=curso-de-pruebas-paypal
2. Click on the 'Add to Cart' …

feat: enrollment creation when an order is processed

---

admin/class-openedx-woocommerce-plugin-admin.php
includes/class-openedx-woocommerce-plugin.php

This feature enables the operator, when processing a refund for a course product, to automatically generate an 'un-enroll' request within the Open edX platform, thus streamlining and expediting the process. Furthermore, the operator will have access to corresponding logs indicating whether the process was successful or not, along with links to the new request.
To test this, you should navigate to an order and create it either manually or using the existing PayPal process to generate a new order. Once the order status is 'processing,' click on the 'refund' button, select the amount, and click 'accept.' Subsequently, the entire process will appear in the order notes, and the associated Enrollment Request ID will be updated.
This is how the refund looks like: 
This process only covers the …

feat: unenroll request when a refund is processed

---

admin/class-openedx-woocommerce-plugin-admin.php
admin/views/class-openedx-woocommerce-plugin-enrollment-info-form.php
admin/views/class-openedx-woocommerce-plugin-settings.php

Some issues that were occurring in the order when adding more products have been resolved, where the product table was experiencing visual glitches. Additionally, some modifications have been made to the CSS of the forms in the settings. The 'client secret' field now has its value hidden, and tooltips have been added to the checkboxes in the enrollment form.
An important point to mention is that, in this case, it's preferable to keep the Client Secret as a 'password' and not display characters initially for security reasons (even though the token, being lengthy, adds a layer of security). It's better to keep it hidden. Another reason is to avoid having to insert JavaScript code because with HTML, it becomes complex to have a visible field for the user with a value like 'ABCD***HIJK' …

fix: bugs in product table fixed & form changes in settings and enrollment

---

includes/model/class-openedx-woocommerce-plugin-api-calls.php

There was a bug that caused an error when you tried to make, for the first time after a while, a new request. This request showed something like 'error getting user' and it was not a problem with the get_user function, it was a problem with the access token. The creation of a new token returns an array containing the 'success' message and the token generated by the API but, when the token is available, it returns only the token value because the process sends a request to the WP database. For that, a check for the access token response was added: when the response is an array it takes the value of the token from the array, when it isn't, it continues the process as always. 
You can test it by changing the expiration time of the access token and attempting to create a new request after the …

fix: access token doesn't generate errors when token expires

---

admin/js/course-id-restriction.js
admin/js/product-type.js
admin/views/class-openedx-woocommerce-plugin-enrollment-info-form.php
includes/class-openedx-woocommerce-plugin.php

Added a JavaScript file that restricts the course ID fields in the enrollment form and product form for Open edX courses, to make the "course-v1:" string at the beginning mandatory. Also, while running the JavaScript code, there were some error messages appearing in the console because the code was trying to get an element that was not present on the page. To fix this issue, an if structure was added to the code to verify if the element is present on the page before using it.
Go to the enrollment form and the product page and try to modify the course ID.

feat: course id fields restriction & js uncaught element bug fixed

---

includes/model/class-openedx-woocommerce-plugin-api-calls.php
includes/model/class-openedx-woocommerce-plugin-enrollment.php

A dynamic approach is implemented between the new endpoints for enrollments and unenrollments and the 'legacy' endpoints that have been functioning currently. The goal is to foster versatility across platforms, allowing both new and existing systems to seamlessly utilize these changes. This transition ensures a progressive and secure adoption of the new implementations across various platforms.
To achieve this, an attempt is made to execute processes using the new endpoints. In case of failure, a fallback to the 'legacy' endpoints is initiated. If the response is positive in the first attempt, the response is returned directly.
Additionally, a minor issue has been addressed where error messages from the API were not displayed as-is but were briefly processed, resulting in limited …

feat: enroll and unenroll process with new and old endpoints

---

admin/css/openedx-woocommerce-plugin-admin.css
admin/views/class-openedx-woocommerce-plugin-enrollment-info-form.php
admin/views/class-openedx-woocommerce-plugin-settings.php

This PR adds:
- Tooltip info in the enrollment request
- Examples in the Open edX domain in settings
- A note to remember to save before generating token

fix: improve tooltip info, examples in the domain settings and doc about save before generate token

---

README.txt
openedx-ecommerce.php

This PR updates the name of the plugin since uploading it to the wordpress registry had issues with the words "plugin" and "woocommerce" for trademark and internal wordpress rules.

fix: updating readme and plugin definition to comply with Wordpress naming conventions

---

.github/workflows/continuous-integration.yml

This change resolves a conflict between the Continuous Integration workflow and the main file's new name, requiring the workflow to point to the new filename.
The CI Workflow is failing due to an out-of-date file name pattern.

fix: corrected main file name in ci github workflow

---

includes/model/class-openedx-woocommerce-plugin-api-calls.php

Fixed an error in the call to the enrollment_process function. The endpoint parameter was missing in the request so it was not being sent correctly.
To test this change simply enter an enrollment and perform an enrollment_request with the "force" box checked.

fix: added missing parameter to process enrollment force

---

.github/workflows/continuous-integration.yml
.github/workflows/upload-release-zip.yml

An important error in the release generation process has been corrected. Previously, when generating a release, the 'zip' file of the plugin was being created with dependencies still tagged with the previous version. In other words, if transitioning from v1.0.0 to v2.0.0, the version tag in the files remained as v1.0.0 due to a workflow order issue.
To address this, we now allow the 'bumpversion' workflow to execute, and only after its successful completion, the 'upload-release-zip.yml' process is triggered. This process generates a zip file with the current version tag and adds it to the finalized release.
"For testing purposes, it's best to fork the repository, manually create an initial version tag so that the workflow can recognize that one already exists and know which version to …

feat: created new workflow for release zip with current version

---

openedx-ecommerce.php

The issue of creating Enrollment Requests during a clean installation of WordPress and plugin installation was attributed to caching problems and checks when creating the table that holds vital request information in the WordPress database. After further investigation, the following errors were resolved:
1. **Misuse of $logs_table Variable:** We identified an error where the variable `$logs_table`, obtained from the `wp_cache_get()` function, was incorrectly being used as the table name. This approach is flawed because the function does not return the table name. Using `$logs_table` for creating the table and conducting existence checks resulted in SQL errors.
2. **Incorrect Variable Usage:** When the table was not found in the cache, SQL was employed to verify its existence in the …

fix: plugin working on clean installation

---

includes/model/class-openedx-woocommerce-plugin-api-calls.php

…
When we add the new endpoint support in #44, we insert a bug. We tried to make an email enrollment, and in the previous version (Palm and Olive), this didn't fail, but we created an enrollment with the JWT token user, which is not the correct behavior.
To fix this, I only changed the second argument in get_enrollment_process_body to use the old form to request (with users). [More info here](https://github.com/openedx/openedx-wordpress-ecommerce/blob/f240dc09e4b14651bb1a78984b4102e408326d04/includes/model/class-openedx-woocommerce-plugin-api-calls.php#L403).
Install this plugin and perform enrollment requests in different versions of Open edX.
Check if you can enroll users and if you can perform course enrollments allowed.
Screenshot of performing an enrollment with a user (Olmo version) …

fix: avoid using the email enrollment endpoint to fix a bug in versions without email support

---

includes/model/class-openedx-woocommerce-plugin-enrollment.php

This small adjustment in the code makes an error that only appeared in a Local execution of the code disappear. Before, when creating a new Enrollment Request manually, a message appeared at the top of the form saying that the Enrollment Action variable was not defined this happened because, in fact, in a new post, there was no enrollment action and we were not checking whether this action was set or not to assign it to an empty variable.
Run the project locally and create a new Enrollment Request.
- [] Tested in a remote environment N/A

fix: undefined variable enrollment action in new enrollment request

---

includes/model/class-openedx-woocommerce-plugin-api-calls.php
includes/model/class-openedx-woocommerce-plugin-enrollment.php
includes/model/class-openedx-woocommerce-plugin-log.php

Now, in the enrollments, an additional piece of information will be displayed, which is the status. The status can be 'success,' 'error,' or 'no process,' indicating whether the last request was successful, encountered an error, or if no process was necessary (in the case of saving the enrollment locally).
Pull the branch locally and run the 'composer install' command to install all plugin dependencies and test. 
To filter and search for enrollments based on their status, it's as simple as typing the desired status into the search bar located at the top right corner of the enrollments.

feat: show enrollment status in enrollments table

---

README.md
README.txt
includes/class-openedx-commerce-i18n.php

This PR:
- Improve double dirname
Pass the $levels parameter to the dirname() call instead of using nested dirname() calls (PHP >= 7.0)
|       |     (Modernize.FunctionCalls.Dirname.Nested)
- Add more documentation
This changes come from common mistakes in WordPress plugins. Mistakes related:
> Incorrect "Tested up to" parameter (readme file):
> This should be the major version of WordPress that this plugin has been tested on. In the case of new plugins, we require it to be the latest version. This is necessary for plugins to be visible in the repository.
> Example: Tested up to: 6.3
> 
> ...
> 
> Failure to disclose third party or external services (readme file):
> Any usage of third party services, such as connecting to an external API, needs to be documented in the readme file.
> 
> …

refactor: improve double dirname and add more documentation of Open edX

---

admin/class-openedx-commerce-admin.php
admin/views/class-openedx-commerce-enrollment-info-form.php
admin/views/class-openedx-commerce-settings.php
composer.json
composer.lock
includes/class-openedx-commerce.php
includes/model/class-openedx-commerce-enrollment.php
phpcs.xml

This PR:
- Adds [nonces](https://developer.wordpress.org/apis/security/nonces/) in the forms of our plugin (settings, enrollment, product and order).
- Removes the exclusion of the **WordPress.Security.NonceVerification.Missing**  alert.
- Changes the action `save_post_shop_order` to `woocommerce_update_order`.
- **Check the tests are passing:** To know if we are following the WordPress standards without avoiding alerts.
- **Check if the plugin works as expected in WordPress:** Principally the workflows
- Save and update the plugin settings ([Reference image](https://github.com/openedx/openedx-wordpress-ecommerce/blob/main/docs/source/_images/how-tos/create_an_openedx_app/openedx-sync-plugin-settings.png))
- Create or edit a manual enrollment. …

fix: remove the exclusion of NonceVerification in phpcs and fix the issues

---

admin/views/class-openedx-commerce-enrollment-info-form.php
includes/model/class-openedx-commerce-enrollment.php
includes/model/class-openedx-commerce-post-type.php
phpcs.xml
utils/openedx-utils.php

This PR:
- Removes the `phpcs:ignore WordPress.WP.I18n.NonSingularStringLiteralContext`
- Changes the text domain used in the internationalization to be congruent with the text domain in the `openedx-commerce.php` header.
- Add a test to check that the text domain is congruent.
- I also excluded composer-setup.php from the phpcs. That is a local file that does not follow the phpcs WordPress standards.
- Check if you can still create an Open edX Enrollment Request.
- Check the tests.
I added woocommerce as part of the rules because we added some text in the woocommerce pages.
This change is part of the work to publish the plugin in the WordPress Plugin Directory.
> Internationalization: Don't use variables or defines as text, context or text domain parameters.
> 
> Please do not use …

fix: internationalization and slug text domain congruence

---

admin/class-openedx-commerce-admin.php
admin/views/class-openedx-commerce-enrollment-info-form.php
admin/views/class-openedx-commerce-settings.php
composer.json
includes/class-openedx-commerce-activator.php
includes/class-openedx-commerce-deactivator.php
includes/class-openedx-commerce-i18n.php
includes/class-openedx-commerce-loader.php
includes/class-openedx-commerce.php
includes/model/class-openedx-commerce-api-calls.php
includes/model/class-openedx-commerce-enrollment.php
includes/model/class-openedx-commerce-log.php
includes/model/class-openedx-commerce-post-type.php
openedx-commerce.php
phpcs.xml
public/class-openedx-commerce-public.php
test/class-enrollment-test.php
utils/openedx-utils.php

This PR adds principally a rule for the naming convention prefix check in the phpcs.xml:
```xml
<rule ref="WordPress.NamingConventions.PrefixAllGlobals">
<properties>
<property name="prefixes" type="array" value="openedx_commerce" />
</properties>
</rule>
```
Following the best practice for naming: https://developer.wordpress.org/plugins/plugin-basics/best-practices/#avoid-naming-collisions
The rest of the changes are adapting the namespace to that format.
This is already uploaded in our stage WordPress installation. You can check if nothing breaks.
[Credentials](https://share.1password.com/s#uRdQVE_rs5g-3RyrtYudPwWBrF6gfWFIqeZvAVDg0V8)
Error from WordPress.org:
> Generic function/class/define/namespace/option names
> 
> All plugins must have unique function names, namespaces, defines, …

fix: add naming convention rule

---

.github/workflows/upload-release-zip.yml

This PR edit the zip generation GA to exclude unnecessary files and allow manual triggers.
Related: #74 #73 
Excluded files: *.git* .* /test/* /requirements/* /docs/* composer.* *.yaml *.xml Makefile
For composer requirements, we have the `--no-dev` flag.
Example of files not allowed (from #74 #73 ):
```
development tools
unneeded vendor folders for production (bower, node, grunt, etc)
demos
unit tests
08_18-10-54_openedx-commerce/vendor/nikic/php-parser
08_18-10-54_openedx-commerce/vendor/phar-io/manifest/.github
08_18-10-54_openedx-commerce/vendor/phpunit
08_18-10-54_openedx-commerce/vendor/myclabs/deep-copy/.github
08_18-10-54_openedx-commerce/vendor/phpunit/phpunit
08_18-10-54_openedx-commerce/vendor/phpunit/phpunit/src/TextUI/XmlConfiguration/PHPUnit …
```

chore: update the zip GA to manual triggers and exclude unnecessary files

---

README.md
README.txt
admin/views/class-openedx-commerce-settings.php

This PR updates the documentation URL to the Open edX WordPress Commerce doc URL and fixes the Test up to use the latest version.

docs: update doc urls and the test up to 6.5

---

public/class-openedx-commerce-public.php
public/css/openedx-commerce-public.css

This is a quick fix to avoid loading the `openedx-commerce-public.css` in all contexts.
I pass the plugin in a [Plugin Checker.](https://wordpress.org/plugins/plugin-check/) to check we follow the WordPress standards. And I found this warning:
I only removed the queued action because it is not needed. The `openedx-commerce-public.css` doesn't have styles.
With this PR, the plugin checker responds the following:
Check if everything is alright in our stage. This version is in our stage: https://share.1password.com/s#ywKsPlWEUFR__qx_a_ZyoT1jyd8DUJQUs4ycraieSRg

fix: stop using an empty enqued style in all contexts

---

CHANGELOG.md
README.txt
admin/class-openedx-commerce-admin.php
admin/partials/openedx-commerce-admin-display.php
includes/class-openedx-commerce-activator.php
includes/class-openedx-commerce-deactivator.php
includes/class-openedx-commerce-i18n.php
includes/class-openedx-commerce-loader.php
includes/class-openedx-commerce.php
openedx-commerce.php
public/class-openedx-commerce-public.php
public/partials/openedx-commerce-public-display.php
uninstall.php

Updates the URLs to use the Open edX ones and removes unnecessary mentions.

docs: update the github urls and remove unnecessary mentions

---

composer.json
includes/class-openedx-commerce.php

This PR removes the inclusion of the test as a dependency for the plugin and also changes the composer.json to map and autoload the test only in dev mode.
**Context**
We removed the addition of test files in a production plugin in #76, which generated problems because the test module was included in class-openedx-commerce.php. Problem: https://github.com/openedx/openedx-wordpress-ecommerce/issues/62#issuecomment-2189445156
1. Download this plugin with these changes: [ZIP version](https://github.com/eduNEXT/openedx-wordpress-ecommerce/releases/download/v2.0.3/openedx-commerce.zip), that was generated by [this workflow](https://github.com/eduNEXT/openedx-wordpress-ecommerce/actions/runs/9670176669).
2. Install and activate the plugin in a clean WordPress instance (E. g., You can use …

fix: remove the tests' inclusion in the plugin

---

.github/workflows/upload-release-zip.yml

This PR changes the exclusion option to avoid only the `composer.lock` and have the `composer.json` in the zip file.
Related #85 
I only add the `composer.json` because it is the problem in #85

fix: add the composer.json to the zip file

---

admin/class-openedx-commerce-admin.php
phpcs.xml

This PR corrects the text domain, changing `'woocommerce'` to `'openedx-commerce'`, our text-domain. And remove the `'woocommerce'` text domain for the names allowed in our tests.
This PR is related to #87 
- The WP Coding Standard tests are passing.
- You can use this zip version in your environment.
[openedx-commerce-PR89.zip](https://github.com/user-attachments/files/16850775/openedx-commerce-PR89.zip)
- This was also tested in our stage:
https://share.1password.com/s#h_dXnkCnTpVD8gLqKEs5nDXHN6N2CzWVtSdh3qoMTT4

fix: correct the text domains

---

admin/views/class-openedx-commerce-enrollment-info-form.php
public/class-openedx-commerce-public.php
public/js/openedx-commerce-public.js

This PR:
- Removes unused script and style tags.
- Removes queuing in all contexts of an empty script.
- The WP Coding Standard tests are passing.
- You can use this zip version in your environment.
[openedx-commerce.zip](https://github.com/user-attachments/files/16852191/openedx-commerce.zip)
- This was also tested in our stage:
https://share.1password.com/s#h_dXnkCnTpVD8gLqKEs5nDXHN6N2CzWVtSdh3qoMTT4
Related to: #86 #79

fix: remove unused scripts and styles

---

.github/workflows/upload-release-zip.yml
.github/workflows/wordpress-plugin-check.yml
Makefile

This PR adds a GitHub workflow to run [WordPress/plugin-check-action](https://github.com/WordPress/plugin-check-action).
This PR also refactors the workflows.
The zip version generated with this PR is: [openedx-commerce.zip](https://github.com/user-attachments/files/16897592/openedx-commerce.zip)
The test `WordPress Plugin Check / Plugin Check` passed.
This test mounts a WordPress environment, installs our plugin using a version similar to our ZIP release, activates the plugin in this new environment, installs the [Plugin check (PCP)](https://wordpress.org/plugins/plugin-check/) by WordPress Performance Team and Plugin Review Team, and run the test over our plugin.
Checks tested: `i18n_usage`, `code_obfuscation`, `direct_db_queries`, `enqueued_scripts_in_footer`, `enqueued_scripts_size`, …

test: add the wordpress plugin check action

---

docs/source/conf.py

See https://about.readthedocs.com/blog/2024/07/addons-by-default/ for details but
essentially RTD is changing how it's building docs and this will let us handle the
change gracefully.

build: Manually pull some RTD Context.

---

docs/source/how-tos/create_an_openedx_app.rst
docs/source/index.rst
phpcs.xml

This will introduce the `tutor-contrib-wordpress` plugin for `tutor` inside documents. also, clean up some tailing whitespace and reformat an XML file.

docs: add info about tutor-contrib-wordpress plugin

---

CHANGELOG.md
README.txt
admin/class-openedx-commerce-admin.php
includes/class-openedx-commerce.php
openedx-commerce.php

This PR is for fix #101 
- Move the enqueue scripts from `includes/class-openedx-commerce.php` to the admin enqueue_scripts (`admin/class-openedx-commerce-admin.php`).
- Remove the `define_enqueue_scripts` function from `includes/class-openedx-commerce.php` because it is no longer needed.
- Move the enqueue style from `includes/class-openedx-commerce.php` to the admin enqueue_styles (`admin/class-openedx-commerce-admin.php`).
- Provide a default value to options because it is a required parameter.
Use this version and:
- Check the boxes in Enrollment Operation Logs in the Enrollment Requests.
- Check the Open edX Course box in a WooCommerce product.
This video shows how every commit resolves a note/warning in the admin dashboard and, at the end, shows how this does not affect the js and …

fix: admin enqueue order

---

README.txt
includes/model/class-openedx-commerce-enrollment.php

Adds "parent" property to avoid dynamic property creation.
This solves #106 
We were assigning a value to a property called "parent" https://github.com/openedx/openedx-wordpress-ecommerce/blob/e0e636e6b2f5e1af2c824c3f590b0e5b1428698a/includes/model/class-openedx-commerce-enrollment.php#L58
but it wasn't defined before.
In this PR, I only define a property called "parent" to avoid the dynamic property creation.
And also update the tested up version in the docs.
Live link: https://openecommtest.s6-tastewp.com/wp-admin/
I already uploaded the plugin with this version.
<details>
<summary>Credentials</summary>
admin
P^C)W)DOrPa&^KYsOvY8x2P3
</details>
Or you can use this branch to run `make release`, and compress the `openedx-commerce` folder as a ZIP file. Use that as a plugin to upload to …

fix: add parent property to avoid dynamic property
